DEDUP_MAIN	= dedup_main
DEDUP_SORT	= dedup_sort
DEDUP_MERGE	= dedup_merge
EB_SEGMENT	= eb_segment
DEDUP_ANALYSIS	= dedup_analysis
BINS	= $(DEDUP_MAIN) $(DEDUP_SORT) $(DEDUP_MERGE) $(EB_SEGMENT) $(DEDUP_ANALYSIS)

DEDUP_MAIN_SRCS	= dedup_main.cpp rabin.c dedup_common.c fs_reader.cpp scanner.cpp rabin_asm.S 
HDRS	= dedup_types.hpp fs_reader.hpp scanner.hpp dedup_common.h rabin.h
DEDUP_MAIN_OBJS1	= $(DEDUP_MAIN_SRCS:.cpp=.o)
DEDUP_MAIN_OBJS2	= $(DEDUP_MAIN_OBJS1:.c=.o)
DEDUP_MAIN_OBJS		= $(DEDUP_MAIN_OBJS2:.S=.o)
DEDUP_SORT_OBJS		= dedup_sort.o dedup_common.o
DEDUP_MERGE_OBJS	= dedup_merge.o dedup_common.o
EB_SEGMENT_OBJS		= eb_segment.o dedup_common.o
DEDUP_ANALYSIS_OBJS	= dedup_analysis.o dedup_common.o


CFLAGS	= -O2 -Wall
CPPFLAGS = -O2 -Wall
LDFLAGS	= -lcrypto -lstdc++
CC = gcc

all:		$(DEDUP_MAIN) $(DEDUP_SORT) $(DEDUP_MERGE) $(EB_SEGMENT) $(DEDUP_ANALYSIS)

$(DEDUP_MAIN):	$(DEDUP_MAIN_OBJS)

$(DEDUP_SORT):	$(DEDUP_SORT_OBJS)

$(DEDUP_MERGE):	$(DEDUP_MERGE_OBJS)

$(EB_SEGMENT):	$(EB_SEGMENT_OBJS)

$(DEDUP_ANALYSIS): $(DEDUP_ANALYSIS_OBJS)

$(DEDUP_SORT_OBJS) $(DEDUP_MERGE_OBJS) $(DEDUP_MAIN_OBJS) $(EB_SEGMENT_OBJS) $(DEDUP_ANALYSIS_OBJS):	$(HDRS)

clean:
	rm -f $(BINS) *.o
